- name: Check for existing kubelet configuration
  stat:
    path: /etc/kubernetes/kubelet.conf
  register: kubelet_conf

- name: kubeadm token generate
  command: kubeadm token generate
  register: token1
  when: kubelet_conf.stat.exists == False

- name: kubeadm get existing token
  command: sh -c "kubeadm token list | awk '/The default bootstrap token/ { print $1; }'"
  register: token2
  when: kubelet_conf.stat.exists == True

# https://github.com/ansible/ansible/issues/4297
- name: token
  set_fact:
    token: "{{ token1 if kubelet_conf.stat.exists == False else token2 }}"

- name: kubeadm init
  command: "kubeadm init --skip-preflight-checks --token {{ token.stdout }} --kubernetes-version v1.10.2 --apiserver-advertise-address {{ hostvars[groups.nodes[0]].ansible_ssh_host }}"
  args:
    creates: /etc/kubernetes/kubelet.conf

- name: Configure kube-controller-manager cloud provider integration
  blockinfile:
    dest: /etc/kubernetes/manifests/kube-controller-manager.yaml
    insertbefore: 'image: '
    block: "    - --cloud-provider=openstack\n    - --cloud-config=/etc/kubernetes/cloud-config\n    - --allocate-node-cidrs=true\n    - --cluster-cidr=10.96.0.0/16"
